### ISSUE TITLE
continuous-multioutput error

### ISSUE THREAD

**Issue by williamwongys** [NLeSC/mcfly-tutorial#16]
First of all, I must thank you for this wonderful library, it really helps for beginners like me.

However, I got the above error using find_best_architecture, my y is an array of shape( , 8), and the elements are continuous.  I am trying to predict the next price, by output % of the range in 8 price slots.  for example, the 8 price slots could be close-40, close-30, close-20, close-10, close+10, close+20, close+30, close+40.  I break the price range into few of these 8 slots calculating the amount it ranges within the slot.  so (0,0,0.2,0.3,0.5,0.3,0,0)  means 20% of the range in close-20 slot, 30% in close-10 slot, 50% in close+10 slot, 30% in close+20 slot.  Is this output supported?  If not, how to re-model it?  Thanks.

**Comment by dafnevk** [comment]
Glad to hear you find mcfly useful!

Mcfly currently only supports _classification_ tasks. This can be binary or multiclass classification. The output array _y_ must be a binary array of shape (num_samples, num_classes) with the class label for each sample encoded with one-hot-encoding.

I'm afraid I don't understand your problem well enough to suggest remodeling options. You should see if you can remodel your problem so that each sample has exactly one label.

More information on data preprocessing can be found on the [wiki pages of mcfly](https://github.com/NLeSC/mcfly/wiki/Data-preprocessing).

**Comment by williamwongys** [comment]
Ok I have remodeled it as per advised and it is working now, thanks.
