### ISSUE TITLE
Work on powerpoint with introduction

### ISSUE THREAD

**Issue by vincentvanhees** [NLeSC/mcfly-tutorial#3]
@dafnevk commented on [Thu Mar 02 2017](https://github.com/NLeSC/mcfly/issues/115)

Oral explanation in talk or during workshop:
	Explain what deep learning tries to solve
		why should researchers be interested in learning / using deep learning
			they need classification
		what kind / group of research questions fit
		why not use classical statistics (classical vs DL approach)
To avoid creating customized features, if desired & To create novel feature you may not have thought about & To classify complex pattern constructed from simpler patterns (and give cat example)
DL is also partly unexplored terrain and therefore may add novelty to their field
	Explain what mcfly tries to solve
		Ease the hyperparameter and architecture choice
Why would I use it instead of caffe tensor flow
	Specific for time series
It uses tensorflow and keras, and mcfly provides an easy access way to start learning Keras (it has a less steep learning curve)
Up to date with latest trends in 2016 informed by literature
use expertise to make the choices so that the users don’t have to
Explain Logistic regression and/or single node in a neural network?

**Comment by cwmeijer** [comment]
Some things are still missing, everything that is accounted for already now has a presentation slide number in front of its line.

+	Oral explanation in talk or during workshop:
+			Explain what deep learning tries to solve
+				why should researchers be interested in learning / using deep learning
+					they need classification
+				what kind / group of research questions fit
+				why not use classical statistics (classical vs DL approach)
+ S4		To avoid creating customized features, if desired & To create novel feature you may not have thought about & To classify complex pattern constructed from simpler patterns (and give cat example)
+ S4		DL is also partly unexplored terrain and therefore may add novelty to their field
+ S6			Explain what mcfly tries to solve
+ S6				Ease the hyperparameter and architecture choice
			Why would I use it instead of caffe tensor flow
				Specific for time series
+ S6		It uses tensorflow and keras, and mcfly provides an easy access way to start learning Keras (it has a less steep learning curve)
+ S6		Up to date with latest trends in 2016 informed by literature
+ S6		use expertise to make the choices so that the users don’t have to
+ S6		Explain Logistic regression and/or single node in a neural network?

**Comment by vincentvanhees** [comment]
I have expanded the slide notes on slide 4
I have added item "User input" to slide 4

The following items now covered (slide number at beginning of line)
note that slide 3 was added, the slide numbers below correspond to the old slide numbering (1 less than current slide number from slide 3 onwards)
S5 in Why would I use it instead of caffe tensor flow
S5 Specific for time series
S2 Explain what deep learning tries to solve
S2 Why should researchers be interested in learning / using deep learning
S2 they need classification
S3 what kind / group of research questions fit
S2 why not use classical statistics (classical vs DL approach)
